import { Link } from "@tanstack/react-router";
import type { FaqItem } from "@/components/sections/FaqSection";

export const FAQ_PAGE_FAQS: FaqItem[] = [
  { q: 'What types of custom closets do you offer?', a: 'We\'re excited to offer a diverse range of custom closets designed to transform your space and simplify your life. Our offerings include luxurious Walk-in Closets that feel like your personal boutique, space-efficient Reach-in Closets perfect for smaller areas, and specialized options like our Custom Shoe Storage for all you footwear enthusiasts out there. Whether you\'re looking to organize a master bedroom, kid\'s room, or guest space, we\'ve got you covered. Each closet is meticulously tailored to maximize your unique space while reflecting your personal style. From sleek modern designs to classic traditional looks, we work with you to create a closet that\'s not just functional but also a joy to use every day.' },
  { q: 'How does the custom closet design process work?', a: 'We\'ve streamlined our design process to make creating your dream closet as enjoyable as using it! It all kicks off with a complimentary consultation – think of it as a friendly chat where we get to know you and your space. Our expert designer will visit your home, take precise measurements, and listen carefully to your needs and wishes. We\'ll discuss everything from your style preferences to your daily routines, ensuring every detail is considered. Then, using state-of-the-art 3D modeling software, we\'ll create a virtual design that brings your vision to life. You\'ll be able to see exactly how your new closet will look and function, making adjustments until it\'s just right. To get a more detailed look at our step-by-step process, check out our dedicated page. We\'re all about making this journey fun and stress-free for you!' },
  { q: 'What materials are used in your custom closets?', a: 'Quality is at the heart of everything we do, and that starts with the materials we use. We\'ve handpicked a range of high-quality, durable materials that not only look stunning but are built to withstand daily use for years to come. Our selection includes premium wood veneers for a classic, warm look, sleek and modern laminates in a variety of colors and textures, and even eco-friendly options for the environmentally conscious. We also offer a range of metal finishes for hardware and accessories, allowing you to customize every detail. During your consultation, you\'ll have the opportunity to see and feel samples of our materials, helping you choose the perfect combination for your space. Whether you\'re going for a luxe, high-gloss finish or a more natural, textured look, we\'ve got options to suit every style and budget.' },
  { q: 'Do you provide closet accessories?', a: 'Absolutely! We believe it\'s the little things that make a big difference, which is why we offer a wide array of Closet Accessories to put the finishing touches on your perfect space. From elegant jewelry trays that keep your precious items organized and tangle-free, to sturdy belt racks that display your collection with style, we\'ve thought of everything. Tie holders, scarf organizers, pull-out hampers, and even built-in ironing boards – our accessories are designed to make your daily routine smoother and more enjoyable. We also offer adjustable shelving, pull-out mirrors, and valet rods for those who want that extra touch of luxury. During the design process, we\'ll work with you to select the accessories that best fit your lifestyle and storage needs, ensuring every inch of your closet works hard for you.' },
  {
    q: 'Can you customize my closet for a small space?',
    a: (
      <>
        <p>You bet! Our designers are experts at creating efficient Small Space Storage solutions that maximize every square inch. We use clever tricks like vertical storage, multi-functional pieces, and custom-sized components to make even the tiniest closet feel spacious and organized. Whether you're dealing with an awkward corner, a narrow reach-in, or a compact studio apartment, we've got innovative ideas to help you utilize your space to its fullest potential. From floor-to-ceiling shelving to pull-out organizers and hidden compartments, we'll work with you to design a closet that not only fits your space but also enhances it. Don't let a small space cramp your style – let us show you how much potential it really has!</p>
      </>
    ),
  },
  { q: 'How long does it take to install a custom closet?', a: 'We know you\'re excited to start enjoying your new custom closet, and we aim to make the installation process as quick and smooth as possible. Typically, most installations take between one to two days, depending on the size and complexity of your project. For a standard reach-in closet, we can often complete the installation in just one day. Larger walk-in closets or more intricate designs might take two days to ensure everything is perfect. During your consultation, we\'ll assess your specific project and provide a more accurate timeline. Our skilled installation team works efficiently and carefully, always respecting your home and minimizing disruption to your daily life. We\'ll coordinate with you to find an installation time that fits your schedule, and we\'ll keep you updated throughout the process. Before you know it, you\'ll be organizing your clothes in your brand new, custom-designed closet!' },
  { q: 'Do you offer solutions for organizing my pantry?', a: 'Yes, we do! And let us tell you, a well-organized pantry can be a game-changer for your kitchen and your daily life. Our custom Pantry Organization solutions are designed to bring order to the chaos of cans, boxes, and bags that often clutter this space. We offer a range of options, from adjustable shelving that can accommodate items of various heights, to pull-out drawers that make it easy to access items at the back. Custom cabinets can hide away less-used appliances, while open shelving keeps frequently used items within easy reach. We even have specialized storage for spices, oils, and baking supplies. Our designers will work with you to understand your cooking habits and storage needs, creating a pantry that not only looks great but also improves your efficiency in the kitchen. Imagine being able to see and reach everything at a glance – no more forgotten items or duplicate purchases. With our pantry solutions, you\'ll feel like a master chef in your own home!' },
  {
    q: 'What is included in the warranty?',
    a: (
      <>
        <p>We stand behind the quality of our work, which is why we offer a comprehensive warranty on all our custom closets. Our warranty covers both materials and workmanship, giving you peace of mind that your investment is protected. While the specific details can vary based on the products you choose, generally, our warranty covers any defects in materials or manufacturing for a specified period of time. This includes issues like hardware malfunctions, delamination of materials, or any structural problems that might occur under normal use. We also warranty our installation work, ensuring that any issues arising from improper installation will be promptly addressed. For the most up-to-date and detailed information about our warranty coverage, including duration and any specific terms or conditions, we encourage you to reach out directly. If you ever have any concerns or questions about your custom closet, our <Link to="/contact" className="text-primary hover:underline">customer service team</Link> is always here to help!</p>
      </>
    ),
  },
  { q: 'Do you offer custom storage solutions for garages?', a: 'Absolutely! We believe the garage deserves just as much attention as any other room in your house. Our custom Garage Storage solutions are designed to transform this often-overlooked space into an organized, functional area that meets your specific needs. Whether you\'re a DIY enthusiast with a collection of tools to store, a sports fanatic with equipment for every season, or simply looking to maximize your storage space, we\'ve got you covered. Our garage solutions include heavy-duty cabinets perfect for storing power tools and hardware, adjustable shelving systems that can adapt as your needs change, and specialized racks for everything from bikes to golf clubs. We also offer overhead storage options to make use of that valuable ceiling space. During the design process, we\'ll discuss your hobbies, storage needs, and how you use your garage to create a custom solution that not only organizes your items but also makes them easily accessible. Imagine pulling into a clutter-free garage where everything has its place – that\'s what we aim to deliver!' },
  {
    q: 'Can I see examples of your work?',
    a: (
      <>
        <p>Of course! We're proud of the work we do and love showing it off. We've curated a beautiful <Link to="/portfolio" className="text-primary hover:underline">Portfolio</Link> on our website that showcases a wide variety of our custom closet designs and storage solutions. Here, you can browse through photos of real projects we've completed for clients just like you. You'll find examples of walk-in closets that look like high-end boutiques, efficient reach-in designs that maximize small spaces, beautifully organized pantries, and garage transformations that might just inspire you to tackle your own. Our portfolio is regularly updated with our latest projects, so you can see the current trends and innovative solutions we're implementing. It's a great place to gather ideas and envision the possibilities for your own space. And remember, these are just starting points – your custom closet will be uniquely designed to fit your specific needs and style preferences. We encourage you to spend some time exploring our portfolio and noting the features you love. It's a great way to prepare for your consultation and help us understand your vision!</p>
      </>
    ),
  },
  { q: 'What should I do to prepare for installation?', a: 'Great question! A little preparation goes a long way in ensuring a smooth and efficient installation process. First and foremost, we recommend clearing the area where we\'ll be working. For closets, this means removing all clothing, shoes, and personal items. For other spaces like garages or pantries, please remove any stored items. This not only gives our installers clear access but also protects your belongings. It\'s also helpful to remove any nearby furniture or decorative items that might be in the way. If you\'re having flooring installed as part of your custom closet, you might need to make arrangements for that to be completed before our installation. Don\'t worry about moving heavy items – our team can help with that on installation day. We also suggest covering any nearby furniture or flooring to protect them from dust. On the day of installation, please ensure clear access to the work area and the entryways our team will use. If you have any pets, it\'s best to keep them in a separate area for their safety and comfort. Our team will guide you through any additional preparations during the planning stage, and we\'re always happy to answer any questions you might have. With a little prep work, we\'ll have your new custom storage solution installed and ready to use in no time!' },
  { q: 'Are your designs adjustable after installation?', a: 'Flexibility is key when it comes to storage solutions, which is why many of our custom closet systems offer adjustable components. We understand that your needs might change over time – maybe you\'ve developed a new hobby that requires storage space, or perhaps your wardrobe has evolved. That\'s why we design with adaptability in mind. Many of our shelves and rods can be easily repositioned to accommodate changes in your storage needs. For example, you might decide you need more hanging space and less shelf space, or vice versa. Our systems allow for these kinds of adjustments without requiring a complete overhaul. Some of our more advanced systems even include modular components that can be added, removed, or reconfigured as needed. During your initial design consultation, we\'ll discuss your current needs and potential future changes, ensuring that your custom closet can grow and adapt with you. And remember, if you ever need help reconfiguring your space or want to explore more significant changes, our team is always here to assist you. Your satisfaction doesn\'t end with the installation – we\'re committed to ensuring your custom closet continues to meet your needs for years to come.' },
  {
    q: 'What areas do you serve?',
    a: (
      <>
        <p>We proudly serve the entire vibrant and diverse region of South Florida. From the bustling streets of Miami to the sun-soaked beaches of Palm Beach, and everywhere in between, our team is ready to bring organization and style to homes across the area. We understand the unique needs and preferences of South Florida residents, from dealing with humidity to maximizing space in coastal condos. Whether you're in a historic Art Deco home in Miami Beach, a modern high-rise in Fort Lauderdale, or a spacious family home in Boca Raton, we've got you covered. Our service area includes major cities and suburbs throughout Miami-Dade, Broward, and Palm Beach counties. For a complete list of the specific locations we serve, please check out our <Link to="/service-areas" className="text-primary hover:underline">Areas Served</Link> page. If you're unsure whether we cover your area, don't hesitate to reach out – we're always looking for opportunities to expand our service area and bring our custom storage solutions to more South Florida homes!</p>
      </>
    ),
  },
  {
    q: 'How can I schedule a consultation?',
    a: (
      <>
        <p>We've made scheduling a consultation as easy and convenient as possible! You have several options to choose from, depending on what works best for you. The quickest way is to use our online scheduling tool – just click the "Schedule a Free Consultation" button, and you can choose a date and time that fits your schedule. If you prefer a more personal touch, you're welcome to give us a call at <a href="tel:+15619129881" className="text-primary hover:underline">(561) 912-9881</a>. Our friendly team will be happy to find a consultation time that works for you and answer any initial questions you might have. You can also reach out through our <Link to="/contact" className="text-primary hover:underline">Contact Us</Link> page if you'd like to send us a message or have us call you back. We understand that everyone's schedule is different, which is why we offer both in-home and virtual consultations. In-home consultations allow us to see your space in person and take precise measurements, while virtual consultations are a great option if you're short on time or prefer to start the process from the comfort of your couch. Whichever option you choose, our goal is to make the first step towards your dream closet as easy and enjoyable as possible!</p>
      </>
    ),
  },
  { q: 'What payment options do you offer?', a: 'We believe in making the process of getting your custom closet as smooth as possible, and that includes offering a variety of payment options to suit different needs and preferences. We accept all major credit cards, including Visa, MasterCard, American Express, and Discover, which is convenient for many of our clients. If you prefer, we also accept personal checks. For larger projects, we offer financing options. These can range from no-interest plans for shorter terms to longer-term financing with competitive interest rates. During your consultation, your designer can provide more details about our current financing promotions and help you understand which option might be best for your situation. We\'re committed to transparency in our pricing, so you\'ll always know exactly what you\'re paying for. And remember, we offer free consultations with no obligation to buy, so you can explore your options without any pressure.' },
  { q: 'Can I customize my home office with your products?', a: 'Absolutely! With more people working from home than ever before, a well-designed home office has become essential. Our custom Home Office solutions are designed to create a productive, organized, and inspiring workspace tailored to your specific needs and style preferences. We offer a wide range of options, from built-in desks and shelving units to file cabinets and storage systems. Maybe you need a dual-monitor setup with hidden cable management, or perhaps you\'re looking for a creative solution to incorporate a workspace into your living room or bedroom. We can design L-shaped or U-shaped configurations to maximize corner spaces, create floating desks for a modern look, or build floor-to-ceiling bookcases for your books and decorative items. We also offer solutions for storing and organizing office supplies, important documents, and tech gadgets. Our designers will work with you to understand your work habits, storage needs, and the overall aesthetic you\'re aiming for. We\'ll consider factors like natural light, the need for video conferencing backgrounds, and ergonomics to create a space that\'s not just beautiful, but also functional and comfortable for long work hours. With our custom home office solutions, you\'ll have a workspace that inspires productivity and reflects your personal style.' },
  {
    q: 'Do you offer custom solutions for mudrooms?',
    a: (
      <>
        <p>Yes, we do! Mudrooms are one of those spaces that, when well-designed, can make a huge difference in keeping your entire home organized and clutter-free. Our custom Mudroom Storage solutions are designed to create a functional and attractive transition space between the outdoors and your home's interior. We understand that every family's needs are different, which is why we offer a variety of customizable options. This could include built-in benches with shoe storage underneath – perfect for sitting down to take off muddy boots. We can create individual lockers or cubbies for each family member, complete with hooks for coats and bags, and shelves for hats and gloves. For those with pets, we can incorporate special features like built-in pet food storage or a dedicated space for leashes and toys. We also offer solutions for storing seasonal items like umbrellas, sports equipment, or beach gear. Our designers will work with you to understand your family's routines and storage needs, creating a mudroom that not only keeps your entryway organized but also streamlines your comings and goings. With durable, easy-to-clean materials and smart design, we'll help you create a mudroom that can stand up to whatever your family (or the weather) throws at it!</p>
      </>
    ),
  },
  { q: 'How do I care for my custom closet?', a: 'Taking care of your custom closet is surprisingly simple, and with a little regular maintenance, it will continue to look beautiful and function perfectly for years to come. For daily care, a soft, dry cloth is usually all you need to keep surfaces dust-free. For more thorough cleaning, a slightly damp cloth will do the trick – just be sure to dry the surface immediately afterward to prevent any moisture damage. We recommend avoiding harsh chemical cleaners or abrasive materials, as these can damage the finishes. For wood surfaces, you might want to use a gentle wood cleaner occasionally to maintain the luster. For metal components like rods or hooks, a quick wipe with a dry cloth is usually sufficient. If you notice any stubborn marks or stains, please reach out to us before trying any strong cleaning methods – we can advise you on the best approach for your specific materials. It\'s also a good idea to periodically check and tighten any loose hardware like drawer pulls or knobs. If you have adjustable components, be gentle when making adjustments to avoid putting unnecessary stress on the mechanisms. For closets with lighting features, make sure to turn off lights when not in use to extend the life of the bulbs. If you have any moving parts like sliding doors or pull-out racks, keeping them clean and free from debris will ensure smooth operation. Remember, your custom closet is an investment, and a little care goes a long way. If you ever have any specific questions about maintenance or notice any issues, don\'t hesitate to reach out to our customer support team. We\'re always happy to provide advice or schedule a service visit if needed. With proper care, your custom closet will remain a beautiful and functional part of your home for many years to come.' },
  { q: 'Can I update my closet design in the future?', a: 'Absolutely! We understand that life changes, and so do your storage needs. That\'s why many of our systems are designed with future updates in mind. As your lifestyle evolves – maybe you\'ve taken up a new hobby, changed careers, or your family has grown – your storage requirements might change too. The modular nature of many of our designs means we can often add, remove, or reconfigure elements to better suit your new needs. For instance, we might be able to add more hanging space if your wardrobe has expanded or incorporate specialty storage for new items. Even if you\'re looking for a more significant change, like extending your closet or completely redesigning the layout, we can work with you to update your space. Our team can assess your current setup and suggest modifications that will bring your closet up to date with your current lifestyle. We keep detailed records of all our projects, so we\'ll have the specifications of your original design to work from. Whether it\'s a small tweak or a major overhaul, we\'re here to ensure your closet continues to meet your needs and exceed your expectations for years to come.' },
  {
    q: 'What sets your custom closets apart from prefabricated options?',
    a: (
      <>
        <p>Great question! While prefabricated closets might seem like a quick fix, our custom closets offer a world of difference in terms of quality, functionality, and personalization. First and foremost, our closets are designed specifically for your space, taking into account every nook and cranny, sloped ceiling, or awkward corner. This means we maximize every inch of available space, something that's simply not possible with off-the-shelf solutions. We also consider your personal style, daily routines, and specific storage needs. Do you have an extensive shoe collection? We'll create custom shoe storage. Love scarves? We'll incorporate specialized scarf organizers. This level of customization ensures that your closet isn't just a place to store things, but a space that enhances your daily life.</p>
        <p>The quality of materials we use is also superior to most prefabricated options. We source high-grade materials that are built to last, meaning your closet will look great and function perfectly for years to come. Our installation process is also a cut above – our professional installers ensure everything is perfectly fitted and aligned.</p>
        <p>Another key difference is flexibility. Our designs can easily evolve with your changing needs, something that's much harder to achieve with prefabricated units. And let's not forget the impact on your home's value – a custom closet is often seen as a valuable upgrade by potential buyers.</p>
        <p>Lastly, when you choose our custom closets, you're getting more than just a product – you're getting a full-service experience. From the initial design consultation to the final installation and beyond, we're here to ensure you're completely satisfied. To learn more about why custom is the best choice, check out our Why Choose Us page. We think you'll agree that when it comes to creating your perfect storage solution, custom is the way to go!</p>
      </>
    ),
  },
  {
    q: 'What happens if I need support after installation?',
    a: (
      <>
        <p>Your satisfaction is our top priority, and that commitment doesn't end when we finish the installation. We offer ongoing customer support for all our installations to ensure you continue to love your custom closet for years to come. If you encounter any issues or have questions about your closet system, our dedicated support team is just a phone call or email away. Whether you need help adjusting a shelf, have a question about caring for your closet, or are experiencing any problems with the installation, we're here to help.</p>
        <p>For minor issues or questions, we often can provide guidance over the phone or via email. For more complex issues, we can schedule a service visit to address the problem in person. Our team of skilled technicians can handle everything from minor adjustments to more significant repairs if needed.</p>
        <p>We also offer support if you're looking to modify or expand your closet system in the future. As your storage needs change, we can help you explore options to update your closet to better suit your evolving lifestyle.</p>
        <p>To get in touch with our support team, you can visit our Customer Support page on our website, where you'll find contact information and potentially solutions to common questions. You can also call us directly using the number provided during your installation. We pride ourselves on responsive, helpful customer service, so don't hesitate to reach out if you need anything. Your ongoing satisfaction is important to us, and we're always here to ensure your custom closet continues to meet and exceed your expectations.</p>
      </>
    ),
  },
  {
    q: 'Can you help with laundry room organization?',
    a: (
      <>
        <p>Absolutely! We believe a well-organized laundry room can turn a mundane chore into a more pleasant and efficient task. Our custom Laundry Room Organization solutions are designed to maximize functionality in what is often a small and overlooked space. We start by assessing your specific needs – do you need space for sorting, folding, ironing, or hanging clothes to dry? How about storage for detergents, fabric softeners, and other laundry supplies? Once we understand your requirements, we create a custom design that makes the most of your available space.</p>
        <p>Our laundry room solutions can include a variety of features. We might incorporate countertops over front-loading washers and dryers to create a convenient folding station. Pull-out hampers can be added for easy sorting of lights and darks. We can design cabinets and shelving to keep your laundry supplies organized and easily accessible. For those who like to hang-dry delicate items, we can include retractable drying racks or valet rods.</p>
        <p>We also consider the overall flow of your laundry process. For instance, we might create a designated space for clothes that need special care or design a system that makes it easy to move clothes from the washer to the dryer to the folding area. If space allows, we can even incorporate an ironing station or a sink for hand-washing delicates.</p>
        <p>Our designers will work with you to create a laundry room that not only looks great but also improves your efficiency. We use durable, easy-to-clean materials that can stand up to the humidity and frequent use typical in a laundry room. With our custom laundry room organization, you might find yourself actually looking forward to laundry day!</p>
      </>
    ),
  },
  {
    q: 'What should I expect during my design consultation?',
    a: (
      <>
        <p>Your design consultation is an exciting first step towards creating your perfect custom storage solution! During this session, which typically lasts about an hour, our expert designer will work closely with you to understand your needs, preferences, and vision for your space.</p>
        <p>If you've opted for an in-home consultation, we'll start by taking detailed measurements of your space. This allows us to create a design that maximizes every inch. For virtual consultations, we'll guide you through the measurement process or arrange for a separate measurement appointment.</p>
        <p>Next, we'll discuss your storage needs in depth. We'll ask about your daily routines, the items you need to store, and any pain points you're currently experiencing with your storage. This helps us understand not just what you need to store, but how you use your space day-to-day.</p>
        <p>We'll also explore your style preferences. Whether you're looking for something sleek and modern, warm and traditional, or anywhere in between, we'll make note of the aesthetics that appeal to you. We might show you samples of different materials and finishes to help you visualize the possibilities.</p>
        <p>Using all this information, our designer will create a custom 3D rendering of your proposed design right there during the consultation. This allows you to see exactly how your new space will look and function. We'll walk you through the design, explaining the reasoning behind each element and how it addresses your specific needs.</p>
        <p>Throughout the process, we encourage questions and feedback. This is your opportunity to fine-tune the design and ensure it's exactly what you want. We can make adjustments in real-time, so you can see how different options would look.</p>
        <p>Finally, we'll provide you with a detailed quote for the project. There's no pressure to make a decision on the spot – we want you to feel completely comfortable with your choice.</p>
        <p>Remember, our consultations are free and come with no obligation to buy. Our goal is to provide you with a design you love and all the information you need to make the best decision for your home and lifestyle. It's an interactive, collaborative process, and dare we say, it's actually quite fun!</p>
      </>
    ),
  },
  {
    q: 'Are consultations really free, with no obligation to buy?',
    a: (
      <>
        <p>Yes, absolutely! Our consultations are 100% free, and there is truly no obligation to make a purchase. We firmly believe in the value of our custom solutions, and we want you to have the opportunity to explore your options without any pressure or commitment.</p>
        <p>During your consultation, our goal is simply to understand your needs, show you what's possible, and provide you with a detailed design and quote. We want you to have all the information you need to make an informed decision about whether our custom storage solutions are right for you.</p>
        <p>Our designers are passionate about creating beautiful, functional spaces, and they enjoy the process of working with you to bring your vision to life. They're there to offer expert advice and creative solutions, not to push a sale. We believe that once you see the potential for your space and understand the quality and value we offer, you'll be excited about moving forward – but the choice is entirely yours, and we respect that.</p>
        <p>Even if you decide not to proceed with a purchase immediately after the consultation, the design we create for you is yours to keep.</p>
        <p>We've built our business on satisfied customers and word-of-mouth referrals, not high-pressure sales tactics. Our free, no-obligation consultations are a reflection of our confidence in our products and our commitment to customer satisfaction. So feel free to schedule a consultation, explore your options, and dream big – there's no risk, and you might be surprised by what's possible for your space!</p>
      </>
    ),
  },
];