/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DesignProcessRouteImport } from './routes/design-process'
import { Route as CustomerServiceRouteImport } from './routes/customer-service'
import { Route as CustomClosetsRouteImport } from './routes/custom-closets'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAreasStLucieCountyRouteImport } from './routes/service-areas_.st-lucie-county'
import { Route as ServiceAreasPalmBeachCountyRouteImport } from './routes/service-areas_.palm-beach-county'
import { Route as ServiceAreasOkeechobeeCountyRouteImport } from './routes/service-areas_.okeechobee-county'
import { Route as ServiceAreasMiamiDadeCountyRouteImport } from './routes/service-areas_.miami-dade-county'
import { Route as ServiceAreasMartinCountyRouteImport } from './routes/service-areas_.martin-county'
import { Route as ServiceAreasLeeCountyRouteImport } from './routes/service-areas_.lee-county'
import { Route as ServiceAreasIndianRiverCountyRouteImport } from './routes/service-areas_.indian-river-county'
import { Route as ServiceAreasCollierCountyRouteImport } from './routes/service-areas_.collier-county'
import { Route as ServiceAreasBrowardCountyRouteImport } from './routes/service-areas_.broward-county'
import { Route as CustomClosetsWalkInClosetsRouteImport } from './routes/custom-closets_.walk-in-closets'
import { Route as CareersClosetDesignerRouteImport } from './routes/careers_.closet-designer'
import { Route as AccessoriesClosetLightingRouteImport } from './routes/accessories_.closet-lighting'

const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignProcessRoute = DesignProcessRouteImport.update({
  id: '/design-process',
  path: '/design-process',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceRoute = CustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomClosetsRoute = CustomClosetsRouteImport.update({
  id: '/custom-closets',
  path: '/custom-closets',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasStLucieCountyRoute =
  ServiceAreasStLucieCountyRouteImport.update({
    id: '/service-areas_/st-lucie-county',
    path: '/service-areas/st-lucie-county',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasPalmBeachCountyRoute =
  ServiceAreasPalmBeachCountyRouteImport.update({
    id: '/service-areas_/palm-beach-county',
    path: '/service-areas/palm-beach-county',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasOkeechobeeCountyRoute =
  ServiceAreasOkeechobeeCountyRouteImport.update({
    id: '/service-areas_/okeechobee-county',
    path: '/service-areas/okeechobee-county',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasMiamiDadeCountyRoute =
  ServiceAreasMiamiDadeCountyRouteImport.update({
    id: '/service-areas_/miami-dade-county',
    path: '/service-areas/miami-dade-county',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasMartinCountyRoute =
  ServiceAreasMartinCountyRouteImport.update({
    id: '/service-areas_/martin-county',
    path: '/service-areas/martin-county',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasLeeCountyRoute = ServiceAreasLeeCountyRouteImport.update({
  id: '/service-areas_/lee-county',
  path: '/service-areas/lee-county',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndianRiverCountyRoute =
  ServiceAreasIndianRiverCountyRouteImport.update({
    id: '/service-areas_/indian-river-county',
    path: '/service-areas/indian-river-county',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasCollierCountyRoute =
  ServiceAreasCollierCountyRouteImport.update({
    id: '/service-areas_/collier-county',
    path: '/service-areas/collier-county',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasBrowardCountyRoute =
  ServiceAreasBrowardCountyRouteImport.update({
    id: '/service-areas_/broward-county',
    path: '/service-areas/broward-county',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomClosetsWalkInClosetsRoute =
  CustomClosetsWalkInClosetsRouteImport.update({
    id: '/custom-closets_/walk-in-closets',
    path: '/custom-closets/walk-in-closets',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareersClosetDesignerRoute = CareersClosetDesignerRouteImport.update({
  id: '/careers_/closet-designer',
  path: '/careers/closet-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesClosetLightingRoute =
  AccessoriesClosetLightingRouteImport.update({
    id: '/accessories_/closet-lighting',
    path: '/accessories/closet-lighting',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/custom-closets': typeof CustomClosetsRoute
  '/customer-service': typeof CustomerServiceRoute
  '/design-process': typeof DesignProcessRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/service-areas': typeof ServiceAreasRoute
  '/showroom': typeof ShowroomRoute
  '/accessories/closet-lighting': typeof AccessoriesClosetLightingRoute
  '/careers/closet-designer': typeof CareersClosetDesignerRoute
  '/custom-closets/walk-in-closets': typeof CustomClosetsWalkInClosetsRoute
  '/service-areas/broward-county': typeof ServiceAreasBrowardCountyRoute
  '/service-areas/collier-county': typeof ServiceAreasCollierCountyRoute
  '/service-areas/indian-river-county': typeof ServiceAreasIndianRiverCountyRoute
  '/service-areas/lee-county': typeof ServiceAreasLeeCountyRoute
  '/service-areas/martin-county': typeof ServiceAreasMartinCountyRoute
  '/service-areas/miami-dade-county': typeof ServiceAreasMiamiDadeCountyRoute
  '/service-areas/okeechobee-county': typeof ServiceAreasOkeechobeeCountyRoute
  '/service-areas/palm-beach-county': typeof ServiceAreasPalmBeachCountyRoute
  '/service-areas/st-lucie-county': typeof ServiceAreasStLucieCountyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/custom-closets': typeof CustomClosetsRoute
  '/customer-service': typeof CustomerServiceRoute
  '/design-process': typeof DesignProcessRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/service-areas': typeof ServiceAreasRoute
  '/showroom': typeof ShowroomRoute
  '/accessories/closet-lighting': typeof AccessoriesClosetLightingRoute
  '/careers/closet-designer': typeof CareersClosetDesignerRoute
  '/custom-closets/walk-in-closets': typeof CustomClosetsWalkInClosetsRoute
  '/service-areas/broward-county': typeof ServiceAreasBrowardCountyRoute
  '/service-areas/collier-county': typeof ServiceAreasCollierCountyRoute
  '/service-areas/indian-river-county': typeof ServiceAreasIndianRiverCountyRoute
  '/service-areas/lee-county': typeof ServiceAreasLeeCountyRoute
  '/service-areas/martin-county': typeof ServiceAreasMartinCountyRoute
  '/service-areas/miami-dade-county': typeof ServiceAreasMiamiDadeCountyRoute
  '/service-areas/okeechobee-county': typeof ServiceAreasOkeechobeeCountyRoute
  '/service-areas/palm-beach-county': typeof ServiceAreasPalmBeachCountyRoute
  '/service-areas/st-lucie-county': typeof ServiceAreasStLucieCountyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/custom-closets': typeof CustomClosetsRoute
  '/customer-service': typeof CustomerServiceRoute
  '/design-process': typeof DesignProcessRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/service-areas': typeof ServiceAreasRoute
  '/showroom': typeof ShowroomRoute
  '/accessories_/closet-lighting': typeof AccessoriesClosetLightingRoute
  '/careers_/closet-designer': typeof CareersClosetDesignerRoute
  '/custom-closets_/walk-in-closets': typeof CustomClosetsWalkInClosetsRoute
  '/service-areas_/broward-county': typeof ServiceAreasBrowardCountyRoute
  '/service-areas_/collier-county': typeof ServiceAreasCollierCountyRoute
  '/service-areas_/indian-river-county': typeof ServiceAreasIndianRiverCountyRoute
  '/service-areas_/lee-county': typeof ServiceAreasLeeCountyRoute
  '/service-areas_/martin-county': typeof ServiceAreasMartinCountyRoute
  '/service-areas_/miami-dade-county': typeof ServiceAreasMiamiDadeCountyRoute
  '/service-areas_/okeechobee-county': typeof ServiceAreasOkeechobeeCountyRoute
  '/service-areas_/palm-beach-county': typeof ServiceAreasPalmBeachCountyRoute
  '/service-areas_/st-lucie-county': typeof ServiceAreasStLucieCountyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/custom-closets'
    | '/customer-service'
    | '/design-process'
    | '/faq'
    | '/portfolio'
    | '/service-areas'
    | '/showroom'
    | '/accessories/closet-lighting'
    | '/careers/closet-designer'
    | '/custom-closets/walk-in-closets'
    | '/service-areas/broward-county'
    | '/service-areas/collier-county'
    | '/service-areas/indian-river-county'
    | '/service-areas/lee-county'
    | '/service-areas/martin-county'
    | '/service-areas/miami-dade-county'
    | '/service-areas/okeechobee-county'
    | '/service-areas/palm-beach-county'
    | '/service-areas/st-lucie-county'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/custom-closets'
    | '/customer-service'
    | '/design-process'
    | '/faq'
    | '/portfolio'
    | '/service-areas'
    | '/showroom'
    | '/accessories/closet-lighting'
    | '/careers/closet-designer'
    | '/custom-closets/walk-in-closets'
    | '/service-areas/broward-county'
    | '/service-areas/collier-county'
    | '/service-areas/indian-river-county'
    | '/service-areas/lee-county'
    | '/service-areas/martin-county'
    | '/service-areas/miami-dade-county'
    | '/service-areas/okeechobee-county'
    | '/service-areas/palm-beach-county'
    | '/service-areas/st-lucie-county'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/custom-closets'
    | '/customer-service'
    | '/design-process'
    | '/faq'
    | '/portfolio'
    | '/service-areas'
    | '/showroom'
    | '/accessories_/closet-lighting'
    | '/careers_/closet-designer'
    | '/custom-closets_/walk-in-closets'
    | '/service-areas_/broward-county'
    | '/service-areas_/collier-county'
    | '/service-areas_/indian-river-county'
    | '/service-areas_/lee-county'
    | '/service-areas_/martin-county'
    | '/service-areas_/miami-dade-county'
    | '/service-areas_/okeechobee-county'
    | '/service-areas_/palm-beach-county'
    | '/service-areas_/st-lucie-county'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CustomClosetsRoute: typeof CustomClosetsRoute
  CustomerServiceRoute: typeof CustomerServiceRoute
  DesignProcessRoute: typeof DesignProcessRoute
  FaqRoute: typeof FaqRoute
  PortfolioRoute: typeof PortfolioRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  ShowroomRoute: typeof ShowroomRoute
  AccessoriesClosetLightingRoute: typeof AccessoriesClosetLightingRoute
  CareersClosetDesignerRoute: typeof CareersClosetDesignerRoute
  CustomClosetsWalkInClosetsRoute: typeof CustomClosetsWalkInClosetsRoute
  ServiceAreasBrowardCountyRoute: typeof ServiceAreasBrowardCountyRoute
  ServiceAreasCollierCountyRoute: typeof ServiceAreasCollierCountyRoute
  ServiceAreasIndianRiverCountyRoute: typeof ServiceAreasIndianRiverCountyRoute
  ServiceAreasLeeCountyRoute: typeof ServiceAreasLeeCountyRoute
  ServiceAreasMartinCountyRoute: typeof ServiceAreasMartinCountyRoute
  ServiceAreasMiamiDadeCountyRoute: typeof ServiceAreasMiamiDadeCountyRoute
  ServiceAreasOkeechobeeCountyRoute: typeof ServiceAreasOkeechobeeCountyRoute
  ServiceAreasPalmBeachCountyRoute: typeof ServiceAreasPalmBeachCountyRoute
  ServiceAreasStLucieCountyRoute: typeof ServiceAreasStLucieCountyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-process': {
      id: '/design-process'
      path: '/design-process'
      fullPath: '/design-process'
      preLoaderRoute: typeof DesignProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service': {
      id: '/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof CustomerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-closets': {
      id: '/custom-closets'
      path: '/custom-closets'
      fullPath: '/custom-closets'
      preLoaderRoute: typeof CustomClosetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas_/st-lucie-county': {
      id: '/service-areas_/st-lucie-county'
      path: '/service-areas/st-lucie-county'
      fullPath: '/service-areas/st-lucie-county'
      preLoaderRoute: typeof ServiceAreasStLucieCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas_/palm-beach-county': {
      id: '/service-areas_/palm-beach-county'
      path: '/service-areas/palm-beach-county'
      fullPath: '/service-areas/palm-beach-county'
      preLoaderRoute: typeof ServiceAreasPalmBeachCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas_/okeechobee-county': {
      id: '/service-areas_/okeechobee-county'
      path: '/service-areas/okeechobee-county'
      fullPath: '/service-areas/okeechobee-county'
      preLoaderRoute: typeof ServiceAreasOkeechobeeCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas_/miami-dade-county': {
      id: '/service-areas_/miami-dade-county'
      path: '/service-areas/miami-dade-county'
      fullPath: '/service-areas/miami-dade-county'
      preLoaderRoute: typeof ServiceAreasMiamiDadeCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas_/martin-county': {
      id: '/service-areas_/martin-county'
      path: '/service-areas/martin-county'
      fullPath: '/service-areas/martin-county'
      preLoaderRoute: typeof ServiceAreasMartinCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas_/lee-county': {
      id: '/service-areas_/lee-county'
      path: '/service-areas/lee-county'
      fullPath: '/service-areas/lee-county'
      preLoaderRoute: typeof ServiceAreasLeeCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas_/indian-river-county': {
      id: '/service-areas_/indian-river-county'
      path: '/service-areas/indian-river-county'
      fullPath: '/service-areas/indian-river-county'
      preLoaderRoute: typeof ServiceAreasIndianRiverCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas_/collier-county': {
      id: '/service-areas_/collier-county'
      path: '/service-areas/collier-county'
      fullPath: '/service-areas/collier-county'
      preLoaderRoute: typeof ServiceAreasCollierCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas_/broward-county': {
      id: '/service-areas_/broward-county'
      path: '/service-areas/broward-county'
      fullPath: '/service-areas/broward-county'
      preLoaderRoute: typeof ServiceAreasBrowardCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-closets_/walk-in-closets': {
      id: '/custom-closets_/walk-in-closets'
      path: '/custom-closets/walk-in-closets'
      fullPath: '/custom-closets/walk-in-closets'
      preLoaderRoute: typeof CustomClosetsWalkInClosetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers_/closet-designer': {
      id: '/careers_/closet-designer'
      path: '/careers/closet-designer'
      fullPath: '/careers/closet-designer'
      preLoaderRoute: typeof CareersClosetDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories_/closet-lighting': {
      id: '/accessories_/closet-lighting'
      path: '/accessories/closet-lighting'
      fullPath: '/accessories/closet-lighting'
      preLoaderRoute: typeof AccessoriesClosetLightingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CustomClosetsRoute: CustomClosetsRoute,
  CustomerServiceRoute: CustomerServiceRoute,
  DesignProcessRoute: DesignProcessRoute,
  FaqRoute: FaqRoute,
  PortfolioRoute: PortfolioRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  ShowroomRoute: ShowroomRoute,
  AccessoriesClosetLightingRoute: AccessoriesClosetLightingRoute,
  CareersClosetDesignerRoute: CareersClosetDesignerRoute,
  CustomClosetsWalkInClosetsRoute: CustomClosetsWalkInClosetsRoute,
  ServiceAreasBrowardCountyRoute: ServiceAreasBrowardCountyRoute,
  ServiceAreasCollierCountyRoute: ServiceAreasCollierCountyRoute,
  ServiceAreasIndianRiverCountyRoute: ServiceAreasIndianRiverCountyRoute,
  ServiceAreasLeeCountyRoute: ServiceAreasLeeCountyRoute,
  ServiceAreasMartinCountyRoute: ServiceAreasMartinCountyRoute,
  ServiceAreasMiamiDadeCountyRoute: ServiceAreasMiamiDadeCountyRoute,
  ServiceAreasOkeechobeeCountyRoute: ServiceAreasOkeechobeeCountyRoute,
  ServiceAreasPalmBeachCountyRoute: ServiceAreasPalmBeachCountyRoute,
  ServiceAreasStLucieCountyRoute: ServiceAreasStLucieCountyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
