/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomClosetsRouteImport } from './routes/custom-closets'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomClosetsWalkInClosetsRouteImport } from './routes/custom-closets_.walk-in-closets'

const CustomClosetsRoute = CustomClosetsRouteImport.update({
  id: '/custom-closets',
  path: '/custom-closets',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomClosetsWalkInClosetsRoute =
  CustomClosetsWalkInClosetsRouteImport.update({
    id: '/custom-closets_/walk-in-closets',
    path: '/custom-closets/walk-in-closets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom-closets': typeof CustomClosetsRoute
  '/custom-closets/walk-in-closets': typeof CustomClosetsWalkInClosetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom-closets': typeof CustomClosetsRoute
  '/custom-closets/walk-in-closets': typeof CustomClosetsWalkInClosetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom-closets': typeof CustomClosetsRoute
  '/custom-closets_/walk-in-closets': typeof CustomClosetsWalkInClosetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/custom-closets'
    | '/custom-closets/walk-in-closets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/custom-closets'
    | '/custom-closets/walk-in-closets'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/custom-closets'
    | '/custom-closets_/walk-in-closets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CustomClosetsRoute: typeof CustomClosetsRoute
  CustomClosetsWalkInClosetsRoute: typeof CustomClosetsWalkInClosetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/custom-closets': {
      id: '/custom-closets'
      path: '/custom-closets'
      fullPath: '/custom-closets'
      preLoaderRoute: typeof CustomClosetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-closets_/walk-in-closets': {
      id: '/custom-closets_/walk-in-closets'
      path: '/custom-closets/walk-in-closets'
      fullPath: '/custom-closets/walk-in-closets'
      preLoaderRoute: typeof CustomClosetsWalkInClosetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CustomClosetsRoute: CustomClosetsRoute,
  CustomClosetsWalkInClosetsRoute: CustomClosetsWalkInClosetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
